# Generated by Django 4.2.7 on 2024-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystore',
            name='image',
            field=models.ImageField(upload_to='storeImages/'),
        ),
    ]
