# Generated by Django 4.2.7 on 2024-03-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_alter_mystore_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='address',
        ),
    ]
