# Generated by Django 4.1.3 on 2024-03-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_addres_area_alter_addres_city_and_more'),
        ('mystore', '0009_alter_reviewitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystore',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.addres'),
        ),
        migrations.AddField(
            model_name='mystore',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
