# Generated by Django 4.1.3 on 2024-03-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_mystore_address_mystore_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='address',
        ),
        migrations.AddField(
            model_name='mystore',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mystore',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
