# Generated by Django 4.1.3 on 2024-03-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_remove_mystore_address_mystore_city_mystore_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystore',
            name='verification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
