# Generated by Django 5.0.3 on 2024-03-30 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_mystore_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='itemDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='standard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='type',
            field=models.CharField(blank=True, choices=[('School Book', 'School Book'), ('Syllabus Book', 'Syllabus Book'), ('College Book', 'College Book'), ('Notes', 'Notes'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='storeImages/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.storeitem')),
            ],
        ),
    ]
