# Generated by Django 5.0.3 on 2024-03-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_storeitem_itemdesc_storeitem_name_storeitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemImages', to='mystore.storeitem'),
        ),
    ]
