# Generated by Django 5.0.3 on 2024-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_alter_itemimage_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mystore',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='mystore',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='storeImages/'),
        ),
        migrations.AddField(
            model_name='mystore',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='storeImages/'),
        ),
    ]
