# Generated by Django 5.0.3 on 2024-04-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0019_alter_reviewitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_review', to='mystore.storeitem'),
        ),
    ]
