# Generated by Django 5.0.3 on 2024-04-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0021_storeitem_number_of_items_you_have'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='Number of items you have',
            new_name='inStock',
        ),
    ]
