# Generated by Django 5.0.3 on 2024-04-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0022_rename_number_of_items_you_have_storeitem_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystore',
            name='recharge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
