# Generated by Django 5.0.3 on 2024-04-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0023_mystore_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystore',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='storeImages/'),
        ),
    ]
