# Generated by Django 5.0.3 on 2024-04-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0024_mystore_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='status',
        ),
    ]
