# Generated by Django 5.0.3 on 2024-04-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0026_alter_reviewitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='type',
        ),
        migrations.CreateModel(
            name='ItemCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemCategory', to='mystore.storeitem')),
            ],
        ),
    ]
