# Generated by Django 5.0.3 on 2024-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0028_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='category',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
