# Generated by Django 5.0.3 on 2024-04-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0029_alter_itemcategories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
