# Generated by Django 5.0.3 on 2024-05-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0030_alter_itemcategories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='item',
        ),
        migrations.AddField(
            model_name='school',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeSchool', to='mystore.mystore'),
        ),
    ]
