# Generated by Django 5.0.3 on 2024-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0032_school_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storeImages/'),
        ),
    ]
