# Generated by Django 5.0.3 on 2024-06-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0034_school_address_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='open_to_sell',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='topay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
