# Generated by Django 5.0.3 on 2024-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0035_storeitem_end_date_storeitem_open_to_sell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='url',
        ),
    ]
