# Generated by Django 5.0.3 on 2024-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0037_alter_reviewitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
